[project]
name = "tradfi-format"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.regulatory-compliance]
path = "contracts/regulatory-compliance.clar"
depends_on = []

[contracts.asset-exchange]
path = "contracts/asset-exchange.clar"
depends_on = []

[contracts.investor-reputation]
path = "contracts/investor-reputation.clar"
depends_on = []

[contracts.instrument-licensing]
path = "contracts/instrument-licensing.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
